version: "3.8"

services:
  app:
    build: .
    container_name: python_app
    volumes:
      - .:/app
      - ./minio_config.json:/app/minio_config.json
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "app.py"]
